name: Build and push image to docker hub

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag matheuzdreher/streamingserverflask:latest
    - name: Push image to Docker Hub
      run: |
        sudo docker login -u matheuzdreher -p ${{secrets.DOCKER_HUB_TOKEN}}
        sudo docker push matheuzdreher/streamingserverflask:latest
